packages:
  - '.'
  - 'src/*'
  - 'agentica/packages/*'  # custom agentica /core

catalogs:
  libs:
    openai: ^5.2.0
    tstl: ^3.0.0
    type-fest: ^4.37.0
  mcp:
    "@modelcontextprotocol/sdk": ^1.12.0
    "@wrtnlabs/calculator-mcp": ^0.2.1
  typescript:
    ts-node: ^10.9.2
    ts-patch: ^3.3.0
    typescript: ~5.8.3
  typia:
    "@ryoppippi/unplugin-typia": ^2.6.4
    "@samchon/openapi": ^4.3.3
    typia: ^9.3.1
  vite:
    vitest: ^3.0.9